
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: litterbox_development

test:
  <<: *default
  database: litterbox_test

production:
  <<: *default
  database: litterbox_production
